import { useEffect, useState } from 'react';
import { Activity, ArrowUpRight, CalendarDays, CheckCircle2, Clock3, Code2, Download, Filter, Megaphone, MessageCircle, Play, RefreshCw, ShieldCheck, Target, Users, Wifi, WifiOff, Workflow } from 'lucide-react';
import { Badge, Card, Dialog, Drawer, Empty, FormDialog, InfoNote, LinkButton, PageHeading, Progress, Stat, Tabs, Toolbar } from './components';
import { date, go, money, number, percent, useDemo } from './context';
import { exportFile, teamNames } from './Dashboard';
import { APPROVED_TEMPLATES, getMetrics, type MetricFilters, type TrackingEvent } from './domain/engine';

const csv = (rows: (string | number)[][]) => rows.map(row => row.map(value => {
  const text = String(value); const safe = typeof value === 'string' && /^[=+@-]/.test(text) ? `'${text}` : text;
  return `"${safe.replaceAll('"', '""')}"`;
}).join(';')).join('\n');
const timestamp = (value: string) => new Date(value).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo', day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' });
const ratio = (n: number, d: number) => d ? n / d : 0;
const x = (value: number) => `${value.toLocaleString('pt-BR', { maximumFractionDigits: 2 })}×`;
function useRecipeState() {
  const [enabled, setEnabled] = useState<Record<string, boolean>>(() => {
    try { const value = JSON.parse(localStorage.getItem('vp-demo-marketing-recipes') || 'null'); return value && typeof value === 'object' && !Array.isArray(value) ? value : { recovery: true, delivery: true, lead: false }; }
    catch { return { recovery: true, delivery: true, lead: false }; }
  });
  useEffect(() => { try { localStorage.setItem('vp-demo-marketing-recipes', JSON.stringify(enabled)); } catch { /* Session state remains usable without persistence. */ } }, [enabled]);
  return { enabled, setEnabled };
}

export function Marketing({ id }: { id?: string }) {
  const { state, user, can, run, notify } = useDemo();
  const [tab, setTab] = useState('campaigns'), [query, setQuery] = useState(''), [channel, setChannel] = useState(''), [status, setStatus] = useState(''), [campaignId, setCampaignId] = useState(id || ''), [segment, setSegment] = useState('');
  const { enabled, setEnabled } = useRecipeState();
  useEffect(() => { setCampaignId(id || ''); }, [id]);
  const scope: MetricFilters = user.role === 'manager' ? { teamId: user.teamId } : {};
  const m = getMetrics(state, scope), campaign = state.campaigns.find(c => c.id === campaignId), cm = campaign ? getMetrics(state, { ...scope, campaignId: campaign.id }) : undefined;
  const attributedRevenue = state.campaigns.reduce((sum, c) => sum + getMetrics(state, { ...scope, campaignId: c.id }).revenueCents, 0);
  const campaigns = state.campaigns.filter(c => c.name.toLowerCase().includes(query.toLowerCase()) && (!channel || c.channel === channel) && (!status || c.status === status));
  const paidClientIds = new Set(state.orders.filter(o => o.paidAt).map(o => o.clientId));
  const contacts = user.role === 'manager' ? state.clients.filter(c => state.users.find(u => u.id === c.ownerId)?.teamId === user.teamId) : state.clients;
  const segments = [
    { id: 'new', label: 'Novos compradores', description: 'Primeira compra registrada no ciclo.', items: contacts.filter(c => paidClientIds.has(c.id) && c.newBuyer), icon: <Target size={21} /> },
    { id: 'recurring', label: 'Compradores anteriores', description: 'Clientes com histórico anterior ao ciclo.', items: contacts.filter(c => paidClientIds.has(c.id) && !c.newBuyer), icon: <Users size={21} /> },
    { id: 'paid-leads', label: 'Leads de mídia paga', description: 'Origem mídia paga, sem pagamento registrado.', items: contacts.filter(c => !paidClientIds.has(c.id) && c.origin === 'Mídia paga'), icon: <Megaphone size={21} /> },
    { id: 'organic-leads', label: 'Leads de outras origens', description: 'Orgânico, indicação ou cadastro manual.', items: contacts.filter(c => !paidClientIds.has(c.id) && c.origin !== 'Mídia paga'), icon: <MessageCircle size={21} /> },
  ];
  const selectedSegment = segments.find(s => s.id === segment);
  const recipes = [
    { id: 'recovery', title: 'Recuperar pagamento', trigger: 'Pedido aguardando pagamento', action: 'Criar tarefa de retorno comercial', detail: 'Revisar o pedido e escolher o contato apropriado antes de retornar ao cliente.' },
    { id: 'delivery', title: 'Acompanhar entrega', trigger: 'Consulta entregue', action: 'Criar tarefa de acompanhamento', detail: 'Confirmar que o cliente recebeu e conseguiu abrir o relatório.' },
    { id: 'lead', title: 'Receber novo lead', trigger: 'Novo contato registrado', action: 'Criar tarefa de qualificação', detail: 'Identificar a intenção de compra e o próximo passo do atendimento.' },
  ];
  const testRecipe = (recipe: typeof recipes[number]) => {
    if (!can('marketing.send') || !can('tasks.write') || !enabled[recipe.id]) return;
    const next = run('task.create', { title: `Teste: ${recipe.title} • ${recipe.action}`, clientId: null, ownerId: user.id, dueDate: '2026-10-07', priority: 'normal' }, 'Teste concluído: uma tarefa foi criada para você.');
    if (next) go('/tarefas');
  };
  const exportCampaigns = () => { exportFile('verifica-placa-campanhas.csv', csv([['Campanha', 'Canal', 'Status', 'Mídia BRL', 'Receita atribuída BRL', 'Pagamentos históricos', 'CAC BRL', 'CPA BRL', 'ROAS'], ...campaigns.map(c => { const metric = getMetrics(state, { ...scope, campaignId: c.id }); return [c.name, c.channel, c.status, metric.adsCents / 100, metric.revenueCents / 100, metric.paidOrders, metric.cacCents / 100, metric.cpaCents / 100, metric.roas]; })])); notify('Campanhas visíveis exportadas em CSV.'); };
  return <>
    <PageHeading eyebrow="AQUISIÇÃO E RELACIONAMENTO" title="Marketing" description="Campanhas, segmentos e próximos passos da sua base."><button className="button secondary" onClick={exportCampaigns}><Download size={15} />Exportar campanhas</button></PageHeading>
    <div className="stats-grid four"><Stat label="Investimento em mídia" value={money(m.adsCents)} hint="01 a 06 out · gasto registrado" icon={<Megaphone size={17} />} onClick={() => setTab('campaigns')} /><Stat label="Receita atribuída" value={money(attributedRevenue)} hint="Pagamentos históricos ligados à mídia" icon={<ArrowUpRight size={17} />} onClick={() => setTab('campaigns')} /><Stat label="CAC de mídia" value={money(m.cacCents)} hint={`CPA por pedido ${money(m.cpaCents)}`} icon={<Target size={17} />} onClick={() => setTab('campaigns')} /><Stat label="ROAS de mídia" value={x(m.roas)} hint="Receita atribuída ÷ investimento" icon={<Activity size={17} />} onClick={() => setTab('campaigns')} /></div>
    <Tabs selected={tab} onSelect={setTab} values={[{ id: 'campaigns', label: 'Campanhas', count: state.campaigns.length }, { id: 'segments', label: 'Segmentos', count: contacts.length }, { id: 'automations', label: 'Receitas', count: recipes.length }]} />
    {tab === 'campaigns' && <Card title="Desempenho das campanhas" subtitle="01 a 06 de outubro de 2026 · atribuição da demonstração"><Toolbar value={query} onChange={setQuery} placeholder="Buscar campanha..."><select aria-label="Canal da campanha" value={channel} onChange={e => setChannel(e.target.value)}><option value="">Todos os canais</option>{[...new Set(state.campaigns.map(c => c.channel))].map(c => <option key={c}>{c}</option>)}</select><select aria-label="Estado da campanha" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos os estados</option><option value="active">Ativas</option><option value="paused">Pausadas</option></select></Toolbar>
      {campaigns.length ? <div className="table-scroll"><table><thead><tr><th>Campanha</th><th>Status</th><th>Investimento</th><th>Receita atribuída</th><th>ROAS</th><th>CPA</th><th>Ações</th></tr></thead><tbody>{campaigns.map(c => { const metric = getMetrics(state, { ...scope, campaignId: c.id }); return <tr key={c.id}><td><button className="text-button" onClick={() => setCampaignId(c.id)}>{c.name}</button><small>{c.channel} · {metric.paidOrders} pagamentos</small></td><td><Badge status={c.status} /></td><td>{money(metric.adsCents)}</td><td>{money(metric.revenueCents)}</td><td><span className="positive">{x(metric.roas)}</span></td><td>{money(metric.cpaCents)}</td><td><button className="button secondary small" onClick={() => setCampaignId(c.id)}>Detalhes</button>{can('marketing.send') && <button className="text-button" onClick={() => run('campaign.toggle', { id: c.id }, 'Status da campanha atualizado na demonstração.')}>{c.status === 'active' ? 'Pausar' : 'Ativar'}</button>}</td></tr>; })}</tbody></table></div> : <Empty />}
      <InfoNote>CAC da API Google Ads: indisponível, integração não conectada. O CAC de mídia desta visão usa compradores distintos e campanhas do registro local.</InfoNote>
    </Card>}
    {tab === 'segments' && <><div className="summary-strip"><Users size={18} /><strong>{number(contacts.length)} contatos</strong><span>Distribuídos em quatro segmentos sem sobreposição.</span></div><div className="two-columns">{segments.map(s => <Card key={s.id} className="segment-card" title={s.label} subtitle={s.description}><div className="product-number">{s.icon}{number(s.items.length)}<small>{percent(ratio(s.items.length, contacts.length))} da base</small></div><Progress value={ratio(s.items.length, contacts.length) * 100} /><LinkButton onClick={() => setSegment(s.id)}>Inspecionar segmento</LinkButton></Card>)}</div><InfoNote>Segmentos são calculados por origem e pagamentos. Consentimento, opt-out e critérios de envio precisam ser mapeados antes da integração real.</InfoNote></>}
    {tab === 'automations' && <><div className="three-columns">{recipes.map(recipe => <Card key={recipe.id} className="recipe-card"><div className="recipe-icon"><Workflow size={24} /></div><Badge status={enabled[recipe.id] ? 'active' : 'paused'} /><h2>{recipe.title}</h2><p>{recipe.detail}</p><div className="timeline"><div><strong>Quando</strong><span>{recipe.trigger}</span></div><div><strong>Fazer</strong><span>{recipe.action}</span></div></div><div className="recipe-footer">{can('marketing.send') ? <button className="button secondary small" onClick={() => { setEnabled(previous => ({ ...previous, [recipe.id]: !previous[recipe.id] })); notify('Estado da receita salvo neste navegador.'); }}>{enabled[recipe.id] ? 'Pausar receita' : 'Ativar receita'}</button> : <span className="muted">Consulta da receita</span>}{can('marketing.send') && can('tasks.write') && <button className="button primary small" disabled={!enabled[recipe.id]} onClick={() => testRecipe(recipe)}><Play size={14} />Testar tarefa</button>}</div></Card>)}</div><InfoNote>O teste cria uma tarefa real no ambiente local, atribuída a você. Receitas não executam sozinhas e não enviam mensagens; a ativação fica salva neste navegador.</InfoNote></>}
    {campaign && cm && <Drawer title={campaign.name} close={() => { setCampaignId(''); if (id) go('/marketing'); }}><div className="detail-grid"><div><span>Canal</span><strong>{campaign.channel}</strong></div><div><span>Status</span><Badge status={campaign.status} /></div><div><span>Investimento</span><strong>{money(cm.adsCents)}</strong></div><div><span>Receita atribuída</span><strong>{money(cm.revenueCents)}</strong></div><div><span>Pagamentos</span><strong>{cm.paidOrders}</strong></div><div><span>Novos compradores</span><strong>{cm.newBuyers}</strong></div><div><span>CAC do registro local</span><strong>{money(cm.cacCents)}</strong></div><div><span>CPA</span><strong>{money(cm.cpaCents)}</strong></div><div><span>ROAS</span><strong>{x(cm.roas)}</strong></div><div><span>Orçamento registrado</span><strong>{money(campaign.budgetCents)}</strong></div></div>
      {campaign.channel === 'Google Ads' ? <Card title="Participação em impressões"><div className="distribution-row"><span>Participação</span><Progress value={campaign.impressionShare * 100} /><strong>{percent(campaign.impressionShare)}</strong></div><div className="distribution-row"><span>Perda por orçamento</span><Progress value={campaign.lostBudget * 100} /><strong>{percent(campaign.lostBudget)}</strong></div><div className="distribution-row"><span>Perda por classificação</span><Progress value={campaign.lostRank * 100} /><strong>{percent(campaign.lostRank)}</strong></div><InfoNote>Participação e perdas são amostras sintéticas. Histórico e CAC informado pela API Google Ads estão indisponíveis.</InfoNote></Card> : <InfoNote>Participação em impressões de pesquisa não se aplica a este canal.</InfoNote>}
      <div className="action-stack">{can('marketing.send') && <button className="button primary" onClick={() => run('campaign.toggle', { id: campaign.id }, 'Status da campanha atualizado na demonstração.')}>{campaign.status === 'active' ? 'Pausar campanha' : 'Ativar campanha'}</button>}{can('view.sales') && <button className="button secondary" onClick={() => go(`/vendas?campaignId=${campaign.id}`)}>Ver pedidos atribuídos</button>}</div><InfoNote>Alterações de status são locais e não modificam contas de anúncios externas.</InfoNote>
    </Drawer>}
    {selectedSegment && <Drawer title={selectedSegment.label} close={() => setSegment('')}><p>{selectedSegment.description}</p><div className="summary-strip"><strong>{number(selectedSegment.items.length)} contatos</strong><span>{percent(ratio(selectedSegment.items.length, contacts.length))} da base</span></div><div className="table-scroll"><table><thead><tr><th>Contato</th><th>Origem</th><th>Responsável</th></tr></thead><tbody>{selectedSegment.items.slice(0, 25).map(c => <tr key={c.id}><td><strong>{c.name}</strong><small>{c.id}</small></td><td>{c.origin}</td><td>{state.users.find(u => u.id === c.ownerId)?.name || '—'}</td></tr>)}</tbody></table></div><InfoNote>Mostrando até 25 contatos da amostra. O CSV inclui todo o segmento.</InfoNote><button className="button secondary" onClick={() => { exportFile(`verifica-placa-segmento-${selectedSegment.id}.csv`, csv([['ID', 'Nome', 'Origem', 'Responsável'], ...selectedSegment.items.map(c => [c.id, c.name, c.origin, state.users.find(u => u.id === c.ownerId)?.name || ''])])); notify('Segmento exportado.'); }}><Download size={15} />Exportar segmento</button></Drawer>}
  </>;
}

export function Tracking() {
  const { state, user, notify } = useDemo();
  const [query, setQuery] = useState(''), [status, setStatus] = useState(''), [source, setSource] = useState(''), [eventName, setEventName] = useState(''), [selected, setSelected] = useState<TrackingEvent | null>(null);
  const scoped = state.trackingEvents.filter(event => user.role !== 'manager' || !event.clientId || state.users.find(u => u.id === state.clients.find(c => c.id === event.clientId)?.ownerId)?.teamId === user.teamId);
  const events = scoped.filter(event => `${event.id} ${event.event} ${state.clients.find(c => c.id === event.clientId)?.name || ''}`.toLowerCase().includes(query.toLowerCase()) && (!status || event.status === status) && (!source || event.source === source) && (!eventName || event.event === eventName));
  const exportEvents = () => { exportFile('verifica-placa-eventos.csv', csv([['ID', 'Evento', 'Origem', 'Status', 'Cliente', 'Data UTC'], ...events.map(event => [event.id, event.event, event.source, event.status, event.clientId || '', event.at])])); notify('Eventos filtrados exportados.'); };
  return <><PageHeading eyebrow="EVENTOS E ATRIBUIÇÃO" title="Tracking" description="Inspecione o registro de eventos que conecta aquisição e operação."><button className="button secondary" onClick={exportEvents}><Download size={15} />Exportar eventos</button></PageHeading>
    <div className="stats-grid four"><Stat label="Eventos registrados" value={number(scoped.length)} hint="Amostra sintética · 01 a 06 out" icon={<Activity size={17} />} onClick={() => { setStatus(''); setEventName(''); setSource(''); setQuery(''); }} /><Stat label="Recebidos" value={number(scoped.filter(e => e.status === 'received').length)} hint="Eventos disponíveis para inspeção" icon={<CheckCircle2 size={17} />} onClick={() => setStatus('received')} /><Stat label="Com falha" value={number(scoped.filter(e => e.status === 'failed').length)} hint="Inspecione o evento para revisar" icon={<Clock3 size={17} />} onClick={() => setStatus('failed')} /><Stat label="Origens identificadas" value={number(new Set(scoped.map(e => e.source)).size)} hint="Origem declarada no registro" icon={<Filter size={17} />} onClick={() => setSource('')} /></div>
    <Card title="Registro de eventos" subtitle={`${events.length} eventos na seleção`}><Toolbar value={query} onChange={setQuery} placeholder="Buscar evento, ID ou cliente..."><select value={status} aria-label="Status do evento" onChange={e => setStatus(e.target.value)}><option value="">Todos os status</option><option value="received">Recebidos</option><option value="failed">Com falha</option></select><select value={source} aria-label="Origem do evento" onChange={e => setSource(e.target.value)}><option value="">Todas as origens</option>{[...new Set(scoped.map(e => e.source))].map(value => <option key={value}>{value}</option>)}</select><select value={eventName} aria-label="Tipo de evento" onChange={e => setEventName(e.target.value)}><option value="">Todos os eventos</option>{[...new Set(scoped.map(e => e.event))].map(value => <option key={value}>{value}</option>)}</select>{(query || status || source || eventName) && <button className="text-button" onClick={() => { setQuery(''); setStatus(''); setSource(''); setEventName(''); }}>Limpar filtros</button>}</Toolbar>
      {events.length ? <div className="table-scroll"><table><thead><tr><th>Evento</th><th>Contato</th><th>Origem</th><th>Data</th><th>Status</th><th>Ação</th></tr></thead><tbody>{events.map(event => <tr key={event.id}><td><strong>{event.event}</strong><small>{event.id}</small></td><td>{state.clients.find(c => c.id === event.clientId)?.name || 'Sem contato identificado'}</td><td>{event.source}</td><td>{timestamp(event.at)}</td><td><Badge status={event.status === 'received' ? 'confirmed' : 'failed'}>{event.status === 'received' ? 'Recebido' : 'Falhou'}</Badge></td><td><button className="button secondary small" onClick={() => setSelected(event)}><Code2 size={14} />Inspecionar</button></td></tr>)}</tbody></table></div> : <Empty />}
    </Card>
    <Card title="Como a atribuição será reconciliada" subtitle="Definições previstas para a integração de produção"><div className="three-columns"><div className="metric-tile"><span>Primeiro toque</span><strong>Origem inicial</strong><small>Primeiro contato elegível dentro da janela de atribuição.</small></div><div className="metric-tile"><span>Último toque</span><strong>Antes da compra</strong><small>Último contato elegível anterior ao pagamento.</small></div><div className="metric-tile"><span>Janela prevista</span><strong>7 dias</strong><small>Contada até o pagamento; regras precisam ser reconciliadas.</small></div></div><InfoNote>A amostra registra evento, origem, contato e data. Click IDs, consentimento, touchpoints e ligação evento–pedido ainda não estão disponíveis. Primeiro e último toque são definições planejadas, sem cálculo nesta demonstração.</InfoNote></Card>
    {selected && <Dialog wide title={`Inspecionar ${selected.id}`} close={() => setSelected(null)}><div className="detail-grid"><div><span>Evento</span><strong>{selected.event}</strong></div><div><span>Origem</span><strong>{selected.source}</strong></div><div><span>Recebido em</span><strong>{timestamp(selected.at)}</strong></div><div><span>Estado</span><Badge status={selected.status === 'received' ? 'confirmed' : 'failed'}>{selected.status === 'received' ? 'Recebido' : 'Falhou'}</Badge></div></div>{selected.status === 'failed' && <InfoNote>Falha sintética para revisão. A origem não entregou um resultado válido na amostra; diagnóstico e reprocessamento exigem integração real.</InfoNote>}<h3>Payload sintético</h3><pre className="event-json" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', padding: 18, background: 'var(--bg)', borderRadius: 10, fontSize: 12 }}>{JSON.stringify({ synthetic: true, ...selected, availableDimensions: ['event', 'source', 'clientId', 'at', 'status'] }, null, 2)}</pre><div className="dialog-footer"><button className="button secondary" onClick={() => { exportFile(`${selected.id}.json`, JSON.stringify({ synthetic: true, ...selected }, null, 2), 'application/json;charset=utf-8'); notify('Payload sintético exportado.'); }}><Download size={15} />Exportar JSON</button><button className="button primary" onClick={() => setSelected(null)}>Concluir inspeção</button></div></Dialog>}
  </>;
}

export function WhatsApp() {
  const { state, user, can, run, notify } = useDemo();
  const [selectedId, setSelectedId] = useState('');
  const instances = state.instances.filter(instance => ['owner', 'admin'].includes(user.role) || instance.teamId === user.teamId);
  const selected = instances.find(i => i.id === selectedId);
  const conversations = (id: string) => state.conversations.filter(c => c.instanceId === id);
  const pending = (id: string) => conversations(id).reduce((sum, c) => sum + c.messages.filter(m => m.kind === 'outgoing' && m.status === 'pending').length, 0);
  const totalPending = instances.reduce((sum, instance) => sum + pending(instance.id), 0);
  const toggle = (id: string) => run('instance.toggle', { id }, 'Conexão simulada atualizada. Mensagens pendentes foram reconciliadas quando aplicável.');
  return <><PageHeading eyebrow="CANAIS DE ATENDIMENTO" title="WhatsApp" description="Conexões, capacidades e saúde das instâncias da operação.">{can('view.inbox') && <button className="button secondary" onClick={() => go('/atendimento')}><MessageCircle size={16} />Abrir atendimento</button>}</PageHeading>
    <div className="stats-grid four"><Stat label="Instâncias" value={number(instances.length)} hint="Canais disponíveis para sua equipe" icon={<MessageCircle size={17} />} onClick={() => instances[0] && setSelectedId(instances[0].id)} /><Stat label="Conectadas" value={number(instances.filter(i => i.status === 'connected').length)} hint="Estado da demonstração local" icon={<Wifi size={17} />} onClick={() => { const item = instances.find(i => i.status === 'connected'); if (item) setSelectedId(item.id); else notify('Nenhuma instância conectada nesta equipe.'); }} /><Stat label="Pendentes de envio" value={number(totalPending)} hint="Reconciliadas ao reconectar" icon={<Clock3 size={17} />} onClick={() => { const item = instances.find(i => pending(i.id) > 0); if (item) setSelectedId(item.id); else notify('Nenhuma mensagem aguarda envio nesta equipe.'); }} /><Stat label="Instâncias oficiais" value={number(instances.filter(i => i.type === 'official').length)} hint="Modelos aprovados e janela de 24h" icon={<ShieldCheck size={17} />} onClick={() => { const item = instances.find(i => i.type === 'official'); if (item) setSelectedId(item.id); else notify('Nenhuma instância oficial nesta equipe.'); }} /></div>
    <div className="three-columns">{instances.map(instance => <Card className="instance-card" key={instance.id}><div className={`instance-icon ${instance.status}`}>{instance.status === 'connected' ? <Wifi size={25} /> : <WifiOff size={25} />}</div><div className="summary-strip"><Badge status={instance.type === 'official' ? 'confirmed' : 'waiting'}>{instance.type === 'official' ? 'API oficial' : 'Alternativa'}</Badge><Badge status={instance.status} /></div><h2>{instance.name}</h2><p>{instance.number}</p><div className="detail-grid"><div><span>Equipe</span><strong>{teamNames[instance.teamId] || instance.teamId}</strong></div><div><span>Conversas</span><strong>{conversations(instance.id).length}</strong></div><div><span>Fila de envio</span><strong>{pending(instance.id)} mensagens</strong></div><div><span>Última sincronização</span><strong>{timestamp(instance.lastSync)}</strong></div></div><div className="capability-list">{instance.type === 'official' ? <><span><ShieldCheck size={15} />Janela livre de 24 horas</span><span><CheckCircle2 size={15} />Modelos aprovados fora da janela</span></> : <><span><RefreshCw size={15} />Reconexão de sessão</span><span><Clock3 size={15} />Fila preservada enquanto desconectada</span></>}<span><MessageCircle size={15} />Notas internas ficam no atendimento</span></div><div className="recipe-footer"><button className="button secondary small" onClick={() => setSelectedId(instance.id)}>Ver saúde</button>{can('admin.integrations') && <button className={`button ${instance.status === 'disconnected' ? 'primary' : 'secondary'} small`} onClick={() => toggle(instance.id)}>{instance.status === 'connected' ? 'Desconectar' : 'Reconectar'}</button>}</div></Card>)}</div>
    <InfoNote>Conexões e reconexões são simuladas neste navegador. A integração real deverá validar credenciais e saúde no provedor. Nenhum QR code ou mensagem externa é gerado aqui.</InfoNote>
    {selected && <Drawer title={selected.name} close={() => setSelectedId('')}><div className="summary-strip"><Badge status={selected.status} /><span>{selected.type === 'official' ? 'API oficial' : 'Conexão alternativa'}</span></div><div className="detail-grid"><div><span>Número</span><strong>{selected.number}</strong></div><div><span>Equipe</span><strong>{teamNames[selected.teamId] || selected.teamId}</strong></div><div><span>Última sincronização</span><strong>{timestamp(selected.lastSync)}</strong></div><div><span>Mensagens pendentes</span><strong>{pending(selected.id)}</strong></div></div><Card title="Capacidades da instância"><div className="capability-list"><span><CheckCircle2 size={16} />Mensagens associadas ao histórico do cliente</span><span><CheckCircle2 size={16} />Notas internas não entram na fila externa</span><span><CheckCircle2 size={16} />Reconexão confirma cada mensagem pendente uma vez</span>{selected.type === 'official' ? <><span><ShieldCheck size={16} />Mensagem livre até 24h após a última mensagem recebida</span><span><ShieldCheck size={16} />Fora da janela, somente modelo aprovado</span></> : <span><RefreshCw size={16} />Sessão alternativa exige acompanhamento da conexão</span>}</div>{selected.type === 'official' && <InfoNote>{APPROVED_TEMPLATES.length} modelos aprovados na demonstração: retomar atendimento, confirmação de pagamento e relatório disponível.</InfoNote>}</Card><Card title="Conversas desta instância"><div className="table-scroll"><table><thead><tr><th>Contato</th><th>Estado</th><th>Fila</th></tr></thead><tbody>{conversations(selected.id).map(c => <tr key={c.id}><td>{state.clients.find(client => client.id === c.clientId)?.name || c.clientId}</td><td><Badge status={c.status} /></td><td>{c.messages.filter(m => m.kind === 'outgoing' && m.status === 'pending').length} pendentes</td></tr>)}</tbody></table></div></Card><div className="action-stack">{can('admin.integrations') && <button className="button primary" onClick={() => toggle(selected.id)}>{selected.status === 'connected' ? 'Simular desconexão' : 'Simular reconexão'}</button>}{can('view.inbox') && <button className="button secondary" onClick={() => go('/atendimento')}>Abrir atendimento</button>}</div><InfoNote>Notas e mensagens existentes são preservadas ao mudar a conexão. O estado conectado representa somente a simulação local.</InfoNote></Drawer>}
  </>;
}

export function Reports() {
  const { state, user, can, notify } = useDemo();
  const [report, setReport] = useState('financial'), [from, setFrom] = useState('2026-10-01'), [to, setTo] = useState('2026-10-06'), [teamId, setTeamId] = useState(''), [campaignId, setCampaignId] = useState(''), [periodDialog, setPeriodDialog] = useState(false);
  const scope = { from, to, teamId: user.role === 'manager' ? user.teamId : teamId, campaignId };
  const m = getMetrics(state, scope);
  const days: string[] = []; for (const d = new Date(`${from}T12:00:00Z`); d <= new Date(`${to}T12:00:00Z`) && days.length < 31; d.setUTCDate(d.getUTCDate() + 1)) days.push(d.toISOString().slice(0, 10));
  const daily = days.map(day => getMetrics(state, { ...scope, from: day, to: day }));
  const campaigns = state.campaigns.filter(c => !campaignId || c.id === campaignId).map(c => ({ campaign: c, metric: getMetrics(state, { ...scope, campaignId: c.id }) }));
  const orders = state.orders.filter(order => {
    const day = (order.paidAt || state.clients.find(c => c.id === order.clientId)?.createdAt || '').slice(0, 10);
    const ownerId = order.assistedBy || state.clients.find(c => c.id === order.clientId)?.ownerId;
    return day >= from && day <= to && (!campaignId || order.campaignId === campaignId) && (!scope.teamId || state.users.find(u => u.id === ownerId)?.teamId === scope.teamId);
  });
  const statuses = ['delivered', 'processing', 'failed', 'cancelled', 'waiting'] as const;
  const labels = { delivered: 'Entregues', processing: 'Em processamento', failed: 'Com falha', cancelled: 'Canceladas', waiting: 'Aguardando pagamento' };
  const download = () => {
    const rows: (string | number)[][] = report === 'financial'
      ? [['Data', 'Receita paga BRL', 'Estornos BRL', 'Líquido BRL', 'Mídia BRL', 'Bureau BRL', 'Taxas BRL', 'Tributo simulado BRL', 'Contribuição BRL', 'Pagamentos históricos', 'Novos compradores'], ...daily.map((d, i) => [days[i], d.revenueCents / 100, d.refundsCents / 100, d.netCents / 100, d.adsCents / 100, d.bureauCents / 100, d.feeCents / 100, d.taxCents / 100, d.contributionCents / 100, d.paidOrders, d.newBuyers])]
      : report === 'campaigns'
        ? [['Campanha', 'Canal', 'De', 'Até', 'Mídia BRL', 'Receita atribuída BRL', 'Pagamentos', 'Novos compradores', 'CAC BRL', 'CPA BRL', 'ROAS'], ...campaigns.map(({ campaign: c, metric: metric }) => [c.name, c.channel, from, to, metric.adsCents / 100, metric.revenueCents / 100, metric.paidOrders, metric.newBuyers, metric.cacCents / 100, metric.cpaCents / 100, metric.roas])]
        : [['Pedido', 'Cliente', 'Produto', 'Pagamento', 'Consulta', 'Data UTC', 'Bureau BRL'], ...orders.map(order => [order.id, state.clients.find(c => c.id === order.clientId)?.name || order.clientId, order.product, order.status, order.consultationStatus, order.paidAt || '', order.bureauCents / 100])];
    exportFile(`verifica-placa-${report}-${from}-${to}.csv`, csv(rows)); notify('Relatório selecionado exportado em CSV.');
  };
  return <><PageHeading eyebrow="ANÁLISE E PRESTAÇÃO DE CONTAS" title="Relatórios" description="Compare períodos e exporte os registros que sustentam seus indicadores."><button className="button secondary" onClick={() => setPeriodDialog(true)}><CalendarDays size={15} />{date(from)} — {date(to)}</button><button className="button primary" onClick={download}><Download size={15} />Exportar relatório</button></PageHeading>
    <div className="dashboard-filters"><span className="live-label"><span className="pulse-dot" />Dados da demonstração</span><div className="filter-controls"><select aria-label="Campanha do relatório" value={campaignId} onChange={e => setCampaignId(e.target.value)}><option value="">Todas as campanhas</option>{state.campaigns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select>{user.role !== 'manager' ? <select aria-label="Equipe do relatório" value={teamId} onChange={e => setTeamId(e.target.value)}><option value="">Todas as equipes</option>{Object.entries(teamNames).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select> : <span className="muted">Equipe {teamNames[user.teamId] || user.teamId}</span>}</div></div>
    <div className="stats-grid four"><Stat label="Receita após estornos" value={money(m.netCents)} hint={`${money(m.refundsCents)} em estornos`} icon={<ArrowUpRight size={17} />} onClick={() => setReport('financial')} /><Stat label="Contribuição após mídia" value={money(m.contributionCents)} hint={`${percent(m.margin)} de margem`} icon={<Target size={17} />} onClick={() => setReport('financial')} /><Stat label="Pagamentos históricos" value={number(m.paidOrders)} hint={`${m.newBuyers} novos compradores`} icon={<Users size={17} />} onClick={() => setReport('campaigns')} /><Stat label="Consultas com falha" value={number(m.failedConsultations)} hint="Status operacional independente" icon={<Activity size={17} />} onClick={() => setReport('service')} /></div>
    <Tabs selected={report} onSelect={setReport} values={[{ id: 'financial', label: 'Financeiro' }, { id: 'campaigns', label: 'Campanhas' }, { id: 'service', label: 'Serviço e consultas' }]} />
    {report === 'financial' && <><Card title="Resultado financeiro diário" subtitle="Valores em reais · tributo simulado de 8% sobre receita após estornos">{daily.some(d => d.paidOrders || d.adsCents) ? <div className="table-scroll"><table><thead><tr><th>Dia</th><th>Receita paga</th><th>Estornos</th><th>Líquido</th><th>Mídia</th><th>Bureau</th><th>Taxas</th><th>Tributo</th><th>Contribuição</th></tr></thead><tbody>{daily.map((d, i) => <tr key={days[i]}><td>{date(days[i])}</td><td>{money(d.revenueCents)}</td><td>{money(d.refundsCents)}</td><td>{money(d.netCents)}</td><td>{money(d.adsCents)}</td><td>{money(d.bureauCents)}</td><td>{money(d.feeCents)}</td><td>{money(d.taxCents)}</td><td><strong>{money(d.contributionCents)}</strong></td></tr>)}</tbody><tfoot><tr><th>Total do período</th><th>{money(m.revenueCents)}</th><th>{money(m.refundsCents)}</th><th>{money(m.netCents)}</th><th>{money(m.adsCents)}</th><th>{money(m.bureauCents)}</th><th>{money(m.feeCents)}</th><th>{money(m.taxCents)}</th><th>{money(m.contributionCents)}</th></tr></tfoot></table></div> : <Empty title="Sem resultado neste período" description="Selecione um período com registros da demonstração." />}</Card><InfoNote>Receita paga preserva pagamentos históricos; estornos são deduzidos no líquido. Mídia é rateada uniformemente pelos seis dias da base. Arredondamentos diários de tributo podem diferir em centavos do total consolidado.</InfoNote></>}
    {report === 'campaigns' && <Card title="Campanhas no período" subtitle="CAC usa novos compradores; CPA usa pagamentos históricos"><div className="table-scroll"><table><thead><tr><th>Campanha</th><th>Mídia</th><th>Receita atribuída</th><th>Pagamentos</th><th>Novos compradores</th><th>CAC</th><th>CPA</th><th>ROAS</th></tr></thead><tbody>{campaigns.map(({ campaign: c, metric: metric }) => <tr key={c.id}><td>{can('view.marketing') ? <button className="text-button" onClick={() => go(`/marketing/${c.id}`)}>{c.name}</button> : <strong>{c.name}</strong>}<small>{c.channel}</small></td><td>{money(metric.adsCents)}</td><td>{money(metric.revenueCents)}</td><td>{metric.paidOrders}</td><td>{metric.newBuyers}</td><td>{money(metric.cacCents)}</td><td>{money(metric.cpaCents)}</td><td>{x(metric.roas)}</td></tr>)}</tbody></table></div><InfoNote>Sem atribuição real da API. As campanhas usam vínculos sintéticos dos pedidos; o resultado global também inclui vendas orgânicas.</InfoNote></Card>}
    {report === 'service' && <><Card title="Distribuição das consultas" subtitle={`${orders.length} pedidos no período selecionado`}>{statuses.map(status => { const count = orders.filter(o => o.consultationStatus === status).length; return <div className="distribution-row" key={status}><Badge status={status}>{labels[status]}</Badge><Progress value={ratio(count, orders.length) * 100} /><strong>{count}</strong><span className="muted">{percent(ratio(count, orders.length))}</span></div>; })}</Card><Card title="Execução por pedido" subtitle="Pagamentos e consultas seguem estados independentes">{orders.length ? <div className="table-scroll"><table><thead><tr><th>Pedido</th><th>Contato</th><th>Pagamento</th><th>Consulta</th><th>Bureau</th><th>Data</th></tr></thead><tbody>{orders.slice(0, 30).map(order => <tr key={order.id}><td>{order.id}</td><td>{state.clients.find(c => c.id === order.clientId)?.name || order.clientId}</td><td><Badge status={order.status} /></td><td><Badge status={order.consultationStatus} /></td><td>{money(order.bureauCents)}</td><td>{date(order.paidAt)}</td></tr>)}</tbody></table></div> : <Empty /> }<InfoNote>A tabela mostra até 30 pedidos. A exportação inclui todos os registros selecionados.</InfoNote></Card></>}
    {can('view.dashboard') && <Card title="A cobertura executiva continua disponível" subtitle="Indicadores legados, produtos, funil, custos, bureau e histórico ficam reunidos na Visão Executiva."><LinkButton onClick={() => go('/dashboard')}>Abrir todos os indicadores executivos</LinkButton></Card>}
    {periodDialog && <FormDialog title="Período do relatório" close={() => setPeriodDialog(false)} submitLabel="Aplicar período" fields={[{ name: 'from', label: 'Data inicial', type: 'date', required: true, value: from }, { name: 'to', label: 'Data final', type: 'date', required: true, value: to }]} onSubmit={values => { if (values.from > values.to) { notify('A data inicial deve ser anterior à final.'); return false; } if (Date.parse(values.to) - Date.parse(values.from) > 30 * 86400000) { notify('Selecione até 31 dias para esta demonstração.'); return false; } setFrom(values.from); setTo(values.to); }} />}
  </>;
}
